{{- if .Values.externalSecretsConfiguration.enabled }}
{{- $root := . }}
{{- if .Values.externalSecretsConfiguration.secretList }}
{{- range $ind, $val := $root.Values.externalSecretsConfiguration.secretList }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $val.name }}-externalsecrets
  namespace: {{ $val.namespace }}
  {{- with $val.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $val.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretStoreRef:
    name: {{ $val.name }}
    kind: ClusterSecretStore
  target:
    name: {{ $val.secrets.targetName | default "default-k8s" }}
    creationPolicy: {{ $val.secrets.targetPolicy | default "Owner" }}
  {{- if $val.secrets.data }}
  data:
    {{- range $item := $val.secrets.data }}
    - secretKey: {{ $item.secretKey | quote }}
      remoteRef:
        key: {{ $item.remoteRef.key | quote }}
        {{- if $item.remoteRef.property }}
        property: {{ $item.remoteRef.property | quote }}
        {{- end }}
        {{- if $item.remoteRef.version }}
        version: {{ $item.remoteRef.version | quote }}
        {{- end }}
    {{- end }}
  {{- else if $val.secrets.secretKeyName }}
  {{- if or $val.secrets.secretKeyName.property $val.secrets.secretKeyName.version }}
  data:
    - secretKey: {{ $val.name | quote }}
      remoteRef:
        {{- if $val.secrets.secretKeyName.key }}
        key: {{ $val.secrets.secretKeyName.key | quote }}
        {{- end }}
        {{- if $val.secrets.secretKeyName.version }}
        version: {{ $val.secrets.secretKeyName.version | quote }}
        {{- end }}
        {{- if $val.secrets.secretKeyName.property }}
        property: {{ $val.secrets.secretKeyName.property | quote }}
        {{- end }}
  {{- else }}
  dataFrom:
    - extract:
        key: {{ $val.secrets.secretKeyName.key | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

